email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohjelmistotekniikka-hy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mluukkai
repo_url: "https://github.com/ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io"
repo_branch: "master"
stats_url: "https://study.cs.helsinki.fi/stats/courses/ohtu2020"

# Kurssikertaan liittyv채t muuttujat:
title: Ohjelmistotekniikka, kev채t 2021

# aikataulut (annetaan muodossa dd.mm)
# HUOM aikataulut t채ytyy antaa merkkijonoina, sill채 muuten 06.04 muuttuisi 6.04
wk1dl: "23.03"
wk2dl: "30.03"
wk3dl: "06.04"
wk4dl: "13.04"
wk5dl: "20.04"
wk6dl: "27.04"
finaldl: "09.05"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed