email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohjelmistotekniikka-hy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mluukkai
repo_url: "https://github.com/ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io"
repo_branch: "master"

# Kurssikertaan liittyvät muuttujat:
title: Ohjelmistotekniikka, kevät 2022

# aikataulut (annetaan muodossa viikonpäivä dd.mm kellonaika)
wk1dl: "tiistai 22.3. klo 23:59"
wk2dl: "tiistai 29.3. klo 23:59"
wk3dl: "tiistai 5.4. klo 23:59"
wk4dl: "tiistai 12.4. klo 23:59"
wk5dl: "tiistai 26.4. klo 23:59"
wk6dl: "tiistai 3.5. klo 23:59"
finaldl: "sunnuntai 15.5. klo 23:59"
code_review_start_date: "keskiviikko 27.4. klo 23:59"

# aloitusluento muodossa viikonpäivä dd.mm kellonaika
# HUOM Kirjoita viikonpäivä isolla, sillä se tulee lauseen alkuun

# ohjausajat
# - Maanantaisin klo 14-16  [zoom](https://helsinki.zoom.us/j/68570587158?pwd=TFhwUXBucExZeVNJZnRydE8yWkNFdz09)
# - Tiistaisin klo 14-16  [zoom](https://helsinki.zoom.us/j/65324719978) (alkaen 23.3.)
# - Torstaisin klo 13-15  [zoom]()
times: 
  - time: "Tiistaisin klo 14-16 kampuksella BK107-luokassa"
  - time: "Keskiviikkoisin klo 14-16 kampuksella BK107-luokassa (poikkeuksena 10.11. klo 15-17)"
  - time: "Torstaisin klo 14-16 [zoom](https://helsinki.zoom.us/j/61671791492?pwd=aW9pczlJZ2RjNXhJVDdjbUU3akd1UT09)"

lecture: "maanantai 1.11. klo 14-16"

# Linkki zoomiin tai youtubeen
lecture_link: "[tallenne](https://youtu.be/i2dwe6RnfUI)"

# seuraava kurssikerta muodossa syksyllä/keväällä [vuosi]. 
# esimerkki syksyllä 2021
# käytetään muun muassa "ei voi jatkaa seuraavalla kurssilla (syksyllä 2021)"
next_course: "syksyllä 2022"

labtool_link: "https://study.cs.helsinki.fi/labtool/courses/TKT20002.2022.K.K.1"

# referenssi-sovellusten linkit
python_reference_app_url: "https://github.com/ohjelmistotekniikka-hy/python-todo-app"
java_reference_app_url: "https://github.com/mluukkai/OtmTodoApp"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

