email: matti.luukkainen@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ohjelmistotekniikka-hy.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  mluukkai
repo_url: "https://github.com/ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io"
repo_branch: "master"

# Kurssikertaan liittyvät muuttujat:
title: Ohjelmistotekniikka, syksy 2021

# aikataulut (annetaan muodossa viikonpäivä dd.mm kellonaika)
wk1dl: "tiistai 9.11. klo 23:59"
wk2dl: "tiistai 16.11. klo 23:59"
wk3dl: "tiistai 23.11. klo 23:59"
wk4dl: "tiistai 30.11. klo 23:59"
wk5dl: "tiistai 7.12. klo 23:59"
wk6dl: "tiistai 14.12. klo 23:59"
finaldl: "sunnuntai 26.12. klo 23:59"
code_review_start_date: "keskiviikko 8.12. klo 23:59"

# aloitusluento muodossa viikonpäivä dd.mm kellonaika
# HUOM Kirjoita viikonpäivä isolla, sillä se tulee lauseen alkuun

# ohjausajat
# - Maanantaisin klo 14-16  [zoom](https://helsinki.zoom.us/j/68570587158?pwd=TFhwUXBucExZeVNJZnRydE8yWkNFdz09)
# - Tiistaisin klo 14-16  [zoom](https://helsinki.zoom.us/j/65324719978) (alkaen 23.3.)
# - Torstaisin klo 13-15  [zoom]()
times: 
  - time: "Maanantaisin (8.11. alkaen) klo 14-16 kampuksella BK107-luokassa"
  - time: "Tiistaisin klo 14-16 kampuksella BK107-luokassa"

lecture: "maanantai 1.11. klo 14-16"

# Linkki zoomiin tai youtubeen
lecture_link: "[zoom](#)"

# seuraava kurssikerta muodossa syksyllä/keväällä [vuosi]. 
# esimerkki syksyllä 2021
# käytetään muun muassa "ei voi jatkaa seuraavalla kurssilla (syksyllä 2021)"
next_course: "keväällä 2022"

labtool_link: "https://study.cs.helsinki.fi/labtool/courses/TKT20002.2021.S.K.1"

# referenssi-sovellusten linkit
python_reference_app_url: "https://github.com/ohjelmistotekniikka-hy/python-todo-app"
java_reference_app_url: "https://github.com/mluukkai/OtmTodoApp"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
